services:
  database:
    image: mysql
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: librebooru
  frontend:
    build: .
    ports:
      - "8080:80"

volumes:
  data:
